### ISSUE TITLE
Especial character 04 (uni066E.calt)

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#73]
It has to be default for Arabic and style for the other scripts

uni066E.init
uniFE91
uniFB5C
uniFB54
uniFB58
uni067D.init
uni067C.init
uniFE97
uniFB60
uniFB68
uniFE9B
uni0751.init
uniFB64
uni0754.init
uni0753.init
uni0752.init
uni0756.init
uni08A0.init
uni0755.init
uni06B9.init
uniFEE7
uni06BC.init
uniFEF3
uni08A9.init
uni06CE.init
uniFE8B
uni063E.init
uniFBFE
uni063D.init
uni0776.init
uni0775.init
uni063F.init
uniFBE6
uni0620.init
uni0777.init
uni077A.init
uni077B.init
uni0767.init
uni0769.init
+
uni069A.fina
uniFEB4
uniFEB2
uniFEB6
uni069C.medi
uni069C.fina
uni069B.medi
uni069B.fina
uni069A.medi
uni06FA.medi
uni06FA.fina
uniFEB8
uni075C.medi
uni075C.fina
uni0770.medi
uni0770.fina
uni076D.medi
uni076D.fina
uni077E.medi
uni077E.fina
uni077D.medi
uni077D.fina
+
What ever we have in Ligatures
uniFD17
uniFD2A

**Comment by graphicore** [comment]
At which position should the replacement happen?
Should the replacement happen by default (i.e. in calt which is on by default) or in a stylistic set?

**Comment by Tarobish** [comment]
At the second one, it has to be default 
When two or more of the "dotless beh" families are neighbors 

KB STUDIO

**Comment by graphicore** [comment]
The second group seems odd to me. How comes that there are `fina` characters but then you expect ligatures to come?

Also, `uni066E.calt` Is an initial character, I just checked, you most certainly want to have the base of the first group replaced. And the second group is probably without the `fina` glyphs.

**Comment by graphicore** [comment]
> When two or more of the "dotless beh" families are neighbors

I get it, you mixed up the the threads :-) Look at them on github ;-)

**Comment by graphicore** [comment]
Ok, I made it as you described (first row in the image). That is:
1. base `uni066E.init`
2. base `uniFEB4`
3. base `uniFEB4`
4. one of these bases: `uniFEF0 uni06CD.fina uniFEAE uni08AA.fina`

But I wonder if you rather intend to have it like this:
1. base `uni066E.init`
2. base `uniFEB4`
3. one of these bases: `uniFEF0 uni06CD.fina uniFEAE uni08AA.fina`

Because the repetition of the `uniFEB4` base in the middle seems odd to me.

![selection_038](https://cloud.githubusercontent.com/assets/393132/12856403/155fc8e2-cc45-11e5-9d9d-35f23566b36d.png)

Note: in the second row the replacement is not happening.

**Comment by Tarobish** [comment]
In the first row it works perfect, it has to be same as well as the second one.
Point of this character is when characters from "dotlessbeh-ar.init" comes before "seen-ar.medi" and "seen-ar.fina" families, its going to be to many tooth so "dotlessbeh-ar.init" will change to"dotlessbeh-ar.calt" to have a better look.
do you know why its not happening in the second one? also can i see it with the "uni069C.fina" and "uniFEB2" please?

**Comment by graphicore** [comment]
> do you know why its not happening in the second one?

Because you did not ask me to do so.

How many `uniFEB4` are happening in a row at max? I have to make one rule for each. Now I have a rule for one and two consecutive `uniFEB4`.

**Comment by Tarobish** [comment]
Sorry i dint get it :(

**Comment by Tarobish** [comment]
thats what you mean?
because we had it here for the ligatures
(The last two row)
![screen shot 2016-02-05 at 6 41 38 pm](https://cloud.githubusercontent.com/assets/8403973/12864215/b778208c-cc38-11e5-9e75-921815cfaced.png)

**Comment by graphicore** [comment]
That's what you asked me to do. But I got it now. I will push an update soon.

**Comment by Tarobish** [comment]
Great :) Many Thanks

**Comment by graphicore** [comment]
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kJRYB2clAnalgzWrKFQbmZubWINrM0tk6Ji8mD0XM2BhTzM0RTFs4OmLImZs6Q9Q4uyDkTE2g5jui0Cj6cahBMQfdDjR3xOQBvZaSWALytJGBoZmugZGugVmIgZGVqaWVsYGekZlJlFItAM94Ucs=

![screen shot 2016-02-06 at 04 04 38](https://cloud.githubusercontent.com/assets/393132/12864307/c70bc01e-cc86-11e5-8519-45e402652a37.png)

**Comment by Tarobish** [comment]
Awesome :) toy are the best
and we have this for all the families, right?

**Comment by graphicore** [comment]
Which families?

**Comment by Tarobish** [comment]
can i see it with the three dots above? just want to check for any possible colliding

**Comment by Tarobish** [comment]
"dotlessbeh-ar.init” families like  "peh-ar.init” or "theh-ar.init”

**Comment by graphicore** [comment]
> can i see it with the three dots above? just want to check for any possible colliding

Can't you write that yourself in http://tarobish.github.io/Katibeh/html/live-testing.html?

> "dotlessbeh-ar.init” families like "peh-ar.init” or "theh-ar.init”

Should be, at least for everything that is decomposed to the base glyphs. It's not necessarily the case, I did only decompose what was needed for the ligatures, but that covers a lot.

**Comment by Tarobish** [comment]
I just did, it docent function in some characters like the second and third one, but we don't have colliding :)
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArolFQQmQn5OYlw7kJRYB2clAnalgzbd7bmxWuLnvxhYFIGsLiLX5xkaFG6tvbLmxMSYvJg+oOCWxBGSMkYGhma6Bka6BWYiBsZWhqZWpsZ6pqUmUUi0ATnwxjQ==

![screen shot 2016-02-05 at 7 15 57 pm](https://cloud.githubusercontent.com/assets/8403973/12864359/07fe6e18-cc3d-11e5-9f6e-a7b541e14884.png)

**Comment by Tarobish** [comment]
As well as these
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArolFQQmQn5OYlw7kJRYB2clAnalgzTfbbmy+sVxB4eY+MH27B0GtUIjJi8kDqk5JLAGZY2RgaKZrYKRrYBZiYGxlaGFlZKlnZGQZpVQLAGjQMVQ=

![screen shot 2016-02-05 at 7 18 26 pm](https://cloud.githubusercontent.com/assets/8403973/12864367/53294af2-cc3d-11e5-8cc7-8a63012a15bd.png)

**Comment by graphicore** [comment]
> I just did, it docent function in some characters 

I've just seen that you used here in the not working examples `uni0634 (final)` which is replaced in `fina` with `uniFEB6`
`uniFEB6` could be decomposed into `uniFEB2 + uniFBB6` but it is not.

Can you give me a complete list of characters that should be decomposed into `uniFEB2 + any_marks` Then the example will work.

> As well as these

You did not ask for these! You asked for stuff ending with `uniFD17 or uniFD2A`

I'm not going to do anything on this issue until you make a proper description of what you want. Please start all over again and make a complete and solid description. Give me examples.

**Comment by Tarobish** [comment]
Sure! :)

**Comment by Tarobish** [comment]
Its all here

uni066E.init
uniFE91
uniFB5C
uniFB54
uniFB58
uni067D.init
uni067C.init
uniFE97
uniFB60
uniFB68
uniFE9B
uni0751.init
uniFB64
uni0754.init
uni0753.init
uni0752.init
uni0756.init
uni08A0.init
uni0755.init
uni06B9.init
uniFEE7
uni06BC.init
uniFEF3
uni08A9.init
uni06CE.init
uniFE8B
uni063E.init
uniFBFE
uni063D.init
uni0776.init
uni0775.init
uni063F.init
uniFBE6
uni0620.init
uni0777.init
uni077A.init
uni077B.init
uni0767.init
uni0769.init
+
uni069A.fina
uniFEB4
uniFEB2
uniFEB6
uni069C.medi
uni069C.fina
uni069B.medi
uni069B.fina
uni069A.medi
uni06FA.medi
uni06FA.fina
uniFEB8
uni075C.medi
uni075C.fina
uni0770.medi
uni0770.fina
uni076D.medi
uni076D.fina
uni077E.medi
uni077E.fina
uni077D.medi
uni077D.fina

**Comment by Tarobish** [comment]
uni066E.init
uniFE91
uniFB5C
uniFB54
uniFB58
uni067D.init
uni067C.init
uniFE97
uniFB60
uniFB68
uniFE9B
uni0751.init
uniFB64
uni0754.init
uni0753.init
uni0752.init
uni0756.init
uni08A0.init
uni0755.init
uni06B9.init
uniFEE7
uni06BC.init
uniFEF3
uni08A9.init
uni06CE.init
uniFE8B
uni063E.init
uniFBFE
uni063D.init
uni0776.init
uni0775.init
uni063F.init
uniFBE6
uni0620.init
uni0777.init
uni077A.init
uni077B.init
uni0767.init
uni0769.init
+
uniFD17
uniFD2A

**Comment by Tarobish** [comment]
all of the characters before "+" has to function with each one after the "+"
means 
uni066E.init + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
or
uniFE91 + + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
as well as all of them with every ligatures which comes from uniFD17 and uniFD2A

**Comment by graphicore** [comment]
> all of the characters before "+" has to function with each one after the "+"
> means
> uni066E.init + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
> or
> uniFE91 + + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
> as well as all of them with every ligatures which comes from uniFD17 and uniFD2A

Sorry, but that's probably the confusing part. It looks to me as if it is enough to look at two glyphs in any case.

**Comment by Tarobish** [comment]
Oh now I get it :) when I'm saying
uni066E.init + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
It means
uni066E.init + uni069A.fina
uni066E.init + uniFEB4
uni066E.init + uniFEB2
uni066E.init + uniFEB6
Or

> uniFE91 + uni069A.fina
> 
> uniFE91 + uniFEB4
> 
> uniFE91 + uniFEB2
> 
> uniFE91 + uniFD17 (every possible characters which comes after generating)
> 
> It means each one separately
> It's the same for the one you did .cal
> Each possible connection

KB STUDIO

**Comment by graphicore** [comment]
> when I'm saying uni066E.init + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
> It means
> […]

Right, but intitially you said something like:

uni066E.init, uniFE91, ... + uni069A.fina, uniFEB4, ... + uniFD17, uniFD2A

Which was very confusing, as it implies it is important that **after the second **part** uniFD17 or uniFD2A must follow. But it isn't as it seems. Then you started throwing piecewise new requirements at me.

> uniFE91 + + uni069A.fina, uniFEB4, uniFEB2, uniFEB6, etc
> as well as all of them with every ligatures which comes from uniFD17 and uniFD2A

"+ +" I hope this is just a typo.

as well as all of them with every ligatures which comes from uniFD17 and uniFD2A

Ok, so it's still not very good explained by you. So let's do a training.

Is the below correct? And could you consider making similar descriptions in the future?

> Replace the `base glyph` of `group 1` when it is followed by a glyph of `group 2`.
> Where: 
> 
> **`group 1`** = uni066E.init, uniFE91, uniFB5C, uniFB54, uniFB58, uni067D.init, uni067C.init, uniFE97,
> uniFB60, uniFB68, uniFE9B, uni0751.init, uniFB64, uni0754.init, uni0753.init, uni0752.init, uni0756.init,
> uni08A0.init, uni0755.init, uni06B9.init, uniFEE7, uni06BC.init, uniFEF3, uni08A9.init, uni06CE.init,
> uniFE8B, uni063E.init, uniFBFE, uni063D.init, uni0776.init, uni0775.init, uni063F.init, uniFBE6,
> uni0620.init, uni0777.init, uni077A.init, uni077B.init, uni0767.init, uni0769.init
> 
> **`group 2`** = uni069A.fina, uniFEB4, uniFEB2, uniFEB6, uni069C.medi, uni069C.fina, uni069B.medi
> uni069B.fina, uni069A.medi, uni06FA.medi, uni06FA.fina, uniFEB8, uni075C.med, uni075C.fina, uni0770.medi, uni0770.fina, uni076D.medi, uni076D.fina, uni077E.medi, uni077E.fina, uni077D.medi,
> uni077D.fina, uniFD17, uniFD2A
> 
> _Note_ that the last two glyphs of `group 2` are ligatures.

**Comment by Tarobish** [comment]
KB STUDIO

**Comment by graphicore** [comment]
This should be fixed now. Please check.

**Comment by Tarobish** [comment]
Great :)
