### ISSUE TITLE
OTF Error

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#76]
After Updating the features, we have this error 
it seems it has something to do with the line 35 and 36 (i guess :) )

![screen shot 2015-12-05 at 10 43 37 pm](https://cloud.githubusercontent.com/assets/8403973/11612120/008e9020-9ba2-11e5-90e2-d7bad9f4a0d0.png)

![screen shot 2015-12-05 at 10 39 49 pm](https://cloud.githubusercontent.com/assets/8403973/11612121/03828aac-9ba2-11e5-91f0-0ecfec27f0db.png)

**Comment by graphicore** [comment]
Interesting, I did not send you anything for the `cmp` feature, just `liga` and `dlig`.

I actually realize that the ligatures you requested to be the default should rather be in `rlig` than in `liga`

**Comment by graphicore** [comment]
Also, I see that there are already `rlig` and `dlig` features defined, I wonder if there is any overlapping between this and what I did.

**Comment by Tarobish** [comment]
Exactly! it should be in "rlig" it my be possible to have overlapping 
also, i think its the same issue with #74 #75
