### ISSUE TITLE
Broken Characters in Urdu & Uyghur

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#79]
Something its broken in letter (Dotless Y
![screen shot 2016-01-14 at 3 25 45 pm](https://cloud.githubusercontent.com/assets/8403973/12341348/d2b5343a-bad5-11e5-90e9-38103ce0ab3f.png)
![screen shot 2016-01-14 at 3 31 35 pm](https://cloud.githubusercontent.com/assets/8403973/12341350/d2d8143c-bad5-11e5-9e29-a9354a8e8733.png)
![screen shot 2016-01-14 at 3 22 57 pm](https://cloud.githubusercontent.com/assets/8403973/12341349/d2d5cae2-bad5-11e5-929c-270cc5a94fa1.png)
![screen shot 2016-01-14 at 3 30 13 pm](https://cloud.githubusercontent.com/assets/8403973/12341352/d2e02712-bad5-11e5-9dc6-b666d17e6d44.png)
![screen shot 2016-01-14 at 3 26 01 pm](https://cloud.githubusercontent.com/assets/8403973/12341351/d2dc38dc-bad5-11e5-9104-c707b2ee092e.png)

eh, Heh.fin and rnoon-ar.fina

**Comment by graphicore** [comment]
Where is this coming from (a pdf loaded into indesign is problematic, pdf is not made for this kind of thing)? Also we don't do specific things for Uyghur and just a tiny bit for Urdu.

Can you reproduce this in the live testing?

I will update the Generated documents in a minute.

**Comment by Tarobish** [comment]
Here is the sample from "persian-arabic2_Katibeh-Regular_18.pdf”
also still i can see the extension parts here
im not able to type this :(

**Comment by graphicore** [comment]
copy and paste it from here: https://github.com/Tarobish/Katibeh/blob/master/Document-Sources/persian-arabic2.txt

**Comment by graphicore** [comment]
Uh, and pic is missing. Which page is it on?

**Comment by Tarobish** [comment]
I think we have to leave this issue
let it be open
i can see the same problem from our Source

http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyVUU1Lw0AQ/StLTgq2bEKsNWf/gZ6kl6JRCjVKCSiKIGmaj9aDIP0LRkpLiOm5v2Mme/OX+HZL8eLFwy4zs++9eTP7ZF3dBqHlWfeulNaBFfoP4clghMIoHCL3b04Hjz5Sx70LkQ/7wTUyRBfg+YbaC2ip0mbVlJwJWlDRrATVKuWYCo45p5pzQaWaqxlVnDeIBI/VnGMdcqKfxF7H7orvl3dxLI/2DZ2WVIBRCJ5SoYm04Jw3gj7VnKotFe0444gjwL8AVBlVOGvBE10BfgwBqL1RbeiTnZ0PaNb6oFAC03Glac9ToGBa2PIfepxoTWOMN9pypFWo5Lyty2YVVMGtStRsO7PWwjISzO4Ju603kjaJgf0227l9FQ4QEfTX5v4b0wvwL5f90PyXtDst6bSke+bYniM9+7DtyO659fwD+BwYJA==

**Comment by Tarobish** [comment]
it was the last page from "persian-arabic2_Katibeh-Regular_18.pdf”

**Comment by Tarobish** [comment]
![screen shot 2016-02-04 at 1 18 50 pm](https://cloud.githubusercontent.com/assets/8403973/12830208/02a66eac-cb43-11e5-9303-8fa9a486be7b.png)
![screen shot 2016-02-04 at 1 16 07 pm](https://cloud.githubusercontent.com/assets/8403973/12830209/058e0b8e-cb43-11e5-8dea-e75e6e7f8eee.png)

**Comment by graphicore** [comment]
Is this about right:
http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6Itis24fardqv2Ygg2KrYp9qtINiz24fZhNin2YTZidiz2Ykg2K/blduL2LHZidqv25Ug2YPbldmE2q/bldmG2K/blSAoNjE4IOKAkyA5MDcpINiz24fYrNin24vYpyDZitin2LHZidiq2YnZviDYqNuV2LHar9uV2YYg2KrZiNmC2YLbh9iyINmK24jYsduI2LQg2YXbh9iy2YnZg9inINiz25DYs9iq2YnZhdmJ2LPZiSDYptin2LPYp9iz2YnYr9inIDY0MCDigJMg2YrZidmE2YkgMTAg2YrbiNix24jYtCDZhduH2LLZidmD2Kcg2LPbkNiz2KrZidmF2YnYs9mJ2YbZiSDYqNuV2LHZvtinINmC2YnZhNiv2YkuINio24fZhNin2LEg2KrbhtuL25XZhtiv2YnZg9mJ2obblSA6IDEuINmD24fahtin2LEg2YXbh9iy2YnZg9mJ2LPZiSDYjCAyLiDZgtuV2LTZgtuV2LEg2YXbh9iy2YnZg9mJ2LPZiSDYjCAiLCJiaWRpIjoicnRsIiwibGFuZyI6ImFyIn0=

![selection_030](https://cloud.githubusercontent.com/assets/393132/12830529/0fc4785c-cb90-11e5-8599-5a3fe92b3dbc.png)

**Comment by Tarobish** [comment]
Yes! Exactly

**Comment by graphicore** [comment]
Can you please make me a live testing page with broken words? One line per word. It would really help me to investigate this further.
Also, you say "Dotless Y" is broken, but I see several broken letters. I think I should know all broken letters eventually, to make sure I repair them all...

**Comment by Tarobish** [comment]
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJwljj0OgkAQha9ithazbAgitTfQytgQRUOCaMgmGo0VIFltbDgDxsYgveeYcS/jLHbzvZ/MO7HVNpHMZ3uHc9ZnMjzIcZSSkMqYONxMomNIKJydJI6DZE1E14J6YVeFVpeYQ405KmhRzZMevHSlb9Cg+tJFAma6wtwAXqCT8Aq1CcATFX5M56EraP4RsgtdwpusDGpjtvoObZct/l9owjKQ3TRuuxYXFvem9sgXrm97g6EtZuz8A/Pxa3k=
there are three characters
one it has to be "uniFBE8" and "uniFBE9" (alefMaksura-ar.medi and alefMaksura-ar.init)
another one its "uniFEEA" or "uniFBA7" (heh-ar.fina or hehgoal-ar.fina)

![screen shot 2016-02-08 at 11 29 56 am](https://cloud.githubusercontent.com/assets/8403973/12896607/b1f0d4d0-ce57-11e5-8c9f-5ae3163ee3a1.png)

سۇلالىسى
دەۋرىگە
كەلگەندە
يارىتىپ
بەرگەن
مۇزىكا
سېستىمىسى

**Comment by graphicore** [comment]
>  one it has to be "uniFBE8" and "uniFBE9" (alefMaksura-ar.medi and alefMaksura-ar.init)

These seem to be missing from the font. I can't find them.

> another one its "uniFEEA" or "uniFBA7" (heh-ar.fina or hehgoal-ar.fina)

These exist in the font

**Comment by graphicore** [comment]
From your example, the letter marked in pink here:

![selection_050](https://cloud.githubusercontent.com/assets/393132/12906563/d6e5fa6a-cee1-11e5-9cde-00349f2257ae.png)

It is actually encoded as uni06D5 ARABIC LETTER AE (Uighur, Kazakh, Kirghiz)

I will replace it just in `fina` with: heh-ar.fina (uniFEEA)? [On an article at wikipedia about Kazakh](https://en.wikipedia.org/wiki/Kazakh_alphabets) I found some backup for that. I was wondering if it also uses the initial and medial forms of Heh, but it doesn't, as it seems.

**Comment by graphicore** [comment]
I think that the hehgoal-ar.fina (`uniFBA7`) character that you mention is a red herring.

The isolated form of `uniFBA7` is `uni06C1` 06C1 ARABIC LETTER HEH GOAL. We have substitutions for it in init, medi and fina to `uniFBA8`, `uniFBA9` and `uniFBA7` So I think there's no indication that `uni06C1` is broken

**Comment by Tarobish** [comment]
lets try it then :)
but we do have them, here they are from UFO
![screen shot 2016-02-08 at 7 33 27 pm](https://cloud.githubusercontent.com/assets/8403973/12907007/2441ab70-ce9b-11e5-93d3-f0859c8fcb27.png)

**Comment by graphicore** [comment]
Oh I see, I just pulled from github and there they are

**Comment by graphicore** [comment]
You added them today?

**Comment by Tarobish** [comment]
Great :) lets finish it

**Comment by Tarobish** [comment]
Yesterday :) i thought it may be something wrong with characters :)
a bit research and then fire :)

**Comment by graphicore** [comment]
Ah, so, unfortunately we do can't use the features generated by glyphs. So Our feature files need to be hand-updated when new glyphs are added. That's maybe also why uniFEEA is not coming up.

**Comment by graphicore** [comment]
Bad thing is when we miss making these updates.

**Comment by Tarobish** [comment]
OH :( should i do this and how?

**Comment by graphicore** [comment]
What exactly? I am adding the features for this issue at the very moment. But if you add any new glyphs that need features, you should open a new issue to inform me.

If you added new glyphs in the past, it would be cool if you know which ones, so we can update our features.

The features for "uniFBE8" and "uniFBE9" are not created by glyphs anyways, I just checked.

**Comment by Tarobish** [comment]
i mean adding the features which you are doing it :)
I didn't know that, actually i know what glyphs
please check these
uni08A8, uni08A8.fina, uni08A8.init, uni08A8.medi

**Comment by graphicore** [comment]
First things first:

![selection_051](https://cloud.githubusercontent.com/assets/393132/12907335/673f6ca6-ceea-11e5-8605-c9cb2439999b.png)

**Comment by Tarobish** [comment]
Awesome :) just perfect

**Comment by graphicore** [comment]
> please check these
> uni08A8, uni08A8.fina, uni08A8.init, uni08A8.medi

They are also not exported by glyphs. It seems also that we should decompose them, so that they will trigger some of our ligatures.

**Comment by Tarobish** [comment]
No don't do that
let them be the way they are

**Comment by graphicore** [comment]
ok.

**Comment by graphicore** [comment]
What's up with this one from your initial description?

![selection_053](https://cloud.githubusercontent.com/assets/393132/12907510/7fd45702-ceec-11e5-9f19-251d25f02d86.png)

**Comment by Tarobish** [comment]
Oh, totally forgot that, let me check it

**Comment by Tarobish** [comment]
Please just replace it with initial form, we do have the characters

**Comment by graphicore** [comment]
Which name/unicode is the isolated form and which is the final form.

**Comment by Tarobish** [comment]
It has to be "uni0679.init" and "uni0679.medi" if I'm not mistaken (I'm not sure)
and here is the iso and final "uni06BB" and "uni06BB.fina" but it risky i couldn't even find the init and medi from "Noto"

**Comment by graphicore** [comment]
06BB  ARABIC LETTER RNOON
• Sindhi

There's also a letter 0679  ARABIC LETTER TTEH
• Urdu

That looks alike https://en.wikipedia.org/wiki/%E1%B9%ACe

Wikipedia says:

> Some layout engines do not properly generate medial and final forms (which should look like ـٹـ and ﭨ) and will render the isolate form ٹ, without joining.

See the wikipedia page for the example letters and some more infos.

**Comment by graphicore** [comment]
If it's `uni0679` it should be replaced by `uni0679.medi` and `uni0679.fina` and `uni0679.init`. But for the replacements I can also use whatever is the right glyph, like `uni06BB.fina`

The same for `uni06BB`, I can replace it with what you suggest if you want me to.

**Comment by graphicore** [comment]
06BB has a quite good wikipedia article https://de.wikipedia.org/wiki/%E1%B9%86un

it says init should be FBA2, medi should be FBA3 and fina should be FBA1

**Comment by graphicore** [comment]
Uh, that's the German wikipedia :-D didn't notice.

**Comment by graphicore** [comment]
Here is the stuff for 0679  TTEH:

FB67  ARABIC LETTER TTEH FINAL FORM
≈ <final> 0679

FB68 ARABIC LETTER TTEH INITIAL FORM
≈ <initial> 0679

FB69 ARABIC LETTER TTEH MEDIAL FORM
≈ <medial> 0679

![selection_054](https://cloud.githubusercontent.com/assets/393132/12908025/b45f3d60-cef2-11e5-9754-1b3de769000b.png)

**Comment by Tarobish** [comment]
Haha :))) exactly, it was my problem because i found it next to  ARABIC LETTER TTEH :) while i was looking for ARABIC LETTER RNOON :)

**Comment by Tarobish** [comment]
OK :) if you think its right to replace them, do this please

**Comment by graphicore** [comment]
Here's RNOON from the unicode PDF

![selection_056](https://cloud.githubusercontent.com/assets/393132/12908063/21592fac-cef3-11e5-88c1-686e6ab00103.png)

**Comment by graphicore** [comment]
ok can we wrap this up. what should be replaced by what?

**Comment by Tarobish** [comment]
in the picture we have the isol form it has to be replace by the inti so
uni06BB replace by uniFB68
later ill check the pdf to see all its right

**Comment by graphicore** [comment]
Ok, so it's all about TTEH, was not all clear to me :-)

**Comment by Tarobish** [comment]
To be honest to me too :) i don't get it, how two letters with the same shape, making different sound :)
its like to have letter R and N with the same shapes :)))))

**Comment by graphicore** [comment]
Yeah, it's kind of stupid. Maybe they don't even make another sound, but that's not how unicode. There is not really a system for unicode encodings I think, they just try to do their best.

SO we have "uni0679.init" and "uni0679.medi". Do you also have the fina form for it? On wikipedia it says TTHE is derived from Ta (062A) So I think we could also make it by decomposition: uni066E.fina +  uni0615

**Comment by Tarobish** [comment]
we already have it by "uni0679" and "uniFB67" for final and isol

**Comment by graphicore** [comment]
I just found out. I'll use uniFB67 uniFB68 uniFB69 and I guess you don't want to risk having ligatures of these?

**Comment by Tarobish** [comment]
Yes :) we don't want to risk it

**Comment by graphicore** [comment]
Ha, now here is the odd thing, all these glyphs are already replaced, the features exist.

**Comment by graphicore** [comment]
Maybe the input text is badly encoded.

**Comment by Tarobish** [comment]
OH

**Comment by graphicore** [comment]
And we already do decomposition, but that means probably that it's ok

**Comment by Tarobish** [comment]
after this projects we are the export :))) we had all of the problems

**Comment by Tarobish** [comment]
so we are fine :)

**Comment by graphicore** [comment]
Hmm, should we find this pesky character in the source file and see what it is supposed to be?

**Comment by Tarobish** [comment]
Let me find something

**Comment by graphicore** [comment]
It llooks like uni06BB (RNOON) not like TTHE which is broader

**Comment by Tarobish** [comment]
تاڭ سۇلالىسىگە بەيئەت قىلغان ئاشىنا تۈرك(بۇ يەردە ئايرىم ساندىكىلېرى كۆزدە تۇتۇلۇدۇ)ئاقسۆڭەكلېرىنىڭ تاڭ سۇلالىسى ئۈچۈن قوشقان تۆھپىلېرىگە قارىتا يەنە تۆۋەندىكىدەكمۇ بايانلار بار:<<640-يىلى لى شىمىن زور كۈچ بىلەن قۇجۇنى،قاغان بۇغدا شەھىرىنى بېسىۋالدى.بۇ ئىشقا تاڭ سۇلالىسىغا ياللانغان ئۇيغۇرلارنىڭ كىببىي قەبىلىسىدىن چىققان سانغۇن كىببى خەلى تۈرك-تاۋغاچ ئارىلاشما قوشۇنلېرىنى ئىشقا سالدى.ئۇلار لۈكچۈندىن(ھازىرقى پىچان ناھىيەسى لۈكچۈن بازىرى)جەڭ ئېچىپ بېشبالىق(ھازىرقى سانجى خۇيزۇ ئاپتۇنۇم ئوبلاستىنىڭ جىمسار ناھىيەسى)قىچە باردى.كىببى خەلى632-يىلى تاۋغاچقا تەسلىم بولغان بولۇپ،676-يىلى ئۆلگۈچە بولغان44يىل ئىچىدە ئۇ ئانا مەركىزىي ئاسىيادا بىھىساپ قان تۆكتى.644-يىلى ئاسىنا شەن يۈز مىڭ كىشىلىك ئارىلاشما قوشۇن بىلەن قارا شەھەر(ئاگنى)نى،648-يىلى كۈسەن،قەشقەر،خوتەن شەھەرلېرىنى ئىگەللىدى.ئاسىنا شەن(ئاسىنا چورا)ئەسلى ئىشبارا قاغاننىڭ قېرىندىشى چۇرلۇق قاغاننىڭ ئوغلى بولۇپ،636-يىلى تاڭ سۇلالىسىغا تەسلىم بولغاندىن655-يىلى ئۆلگۈچە بولغان29يىل ئىچىدە مەركىزىي ئاسىيا تۇپرىقىدا نەچچە تۈمەن كىشىنىڭ قېنىنى تۆكتى.تارىم بوستانلىقىدىكى قارا شەھەر640-يىلى تاڭ سۇلالىسىغا بەيئەت قىلغان بولسىمۇ،648-يىلى ئىسيان كۆتەردى.كۈسەن خانى سۇۋارنا پوسپا(ئالتۇن چېچەك خان)تاڭ سۇلالىسىنىڭ كېڭەيمىچىلىك سىياسىتىگە نارازى بولۇپ،ئولپان تۆلەشنى رەت قىلىپ،قارا شەھەرنىڭ ئىسيانىغا قاتناشتى.ئېلىك قاغاننىڭ ئىنىسى636-يىلى تاڭ سۇلالىسىغا تەسلىم بولغان ئاسىنا شىر قوشۇن باشلاپ،بۇ قارىشىلىق ئىسيانلېرىنى باستۇرۇپ،11مىڭ كىشىنىڭ كاللىسىنى ئېلىپ،بەش شەھەرنى چۆلگە ئايلاندۇرۋەتتى.تاڭ تەيزۇڭ ئۆلگەندە<ساداقەتمەن>ئاسىنا شىر ئۆزىن ئۆلتۈرۈپ،ئۇنىڭ قەبرىسىدە مۇھاپىزەتچى ئەرۋاھ بولدى.

**Comment by graphicore** [comment]
can you isolate it? That's too much text. A word would be enough.

And what is the source?

**Comment by Tarobish** [comment]
تۇنيۇقۇقنىڭ مەسلىھەتى بىلەن ئالدى بىلەن
from wiki

**Comment by Tarobish** [comment]
https://ug.wikipedia.org/wiki/تاڭ_سۇلالىسى

**Comment by graphicore** [comment]
It's not in there, is it? The original source would be helpful. The one that you used to make the initial picture.

By the way, that is one of the reasons why you must post a source to the images you put in here. Just the image is mostly useless. We need both, the image AND the source. Always!

**Comment by graphicore** [comment]
What should I do with that wiki text? I want the string that created the image of the initial description you posted. The text that created this: 

![selection_053](https://cloud.githubusercontent.com/assets/393132/12907510/7fd45702-ceec-11e5-9f19-251d25f02d86.png)

**Comment by Tarobish** [comment]
let me find it, i know where i can fin it :)

**Comment by Tarobish** [comment]
انگريزن اڻويهين صدي ۾ هن شهر جي تعمير و ترقي جون بنيادون وڌيون۔

**Comment by graphicore** [comment]
where is that from?

**Comment by Tarobish** [comment]
our text sample 1 from "Jumhuria" source documents :)

**Comment by graphicore** [comment]
Where is that document? I don't recall a document called like that.

**Comment by graphicore** [comment]
Ah, anyways, there is that glyph in اڻويهين

**Comment by graphicore** [comment]
OK, that is indeed a uni06BB!

**Comment by Tarobish** [comment]
Do you want me to send it to you, i have it

**Comment by graphicore** [comment]
Nah.

**Comment by graphicore** [comment]
so, in this case I need a initial version for uni06BB. Also a medi version would be nice. The fina version is already there.

**Comment by graphicore** [comment]
~~it's strange, but somehow firefox can display the right initial version for it, with out it being in the features.~~

forget it, wrong information.

**Comment by Tarobish** [comment]
ill update the repo for both "Katibeh" and mirza
just added
uniFBA2
uniFBA3

**Comment by graphicore** [comment]
Ok, cool!

**Comment by Tarobish** [comment]
Pull it please :)

**Comment by graphicore** [comment]
ok, from http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIK5JQUAfmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03lt/afbPjZtfNdiBuA0qlJJaAtBgZGJrpGhjpGliGGJhZGRlbGZrqmVkaRSnVAgD6dCZY

![selection_057](https://cloud.githubusercontent.com/assets/393132/12909115/10c91da4-cefe-11e5-816a-9e525fe4ba87.png)

Mirza is updated just in a minute.

**Comment by Tarobish** [comment]
Just perfect :) Thanks

**Comment by graphicore** [comment]
Ok good! see you later. I need some sleep now.

**Comment by Tarobish** [comment]
Sure man :) as always you did great
