### ISSUE TITLE
Ignore Kerning 

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#80]
uniFE8E
uniFE82
uniFE8E.short
+
"uni066E0649" if AlefFina has mark's below
"uni066E06BA" if AlefFina has mark's below

---

uni0627
uni0627.short
+
"uni066E0649" if AlefFina has mark's below
"uni066E06BA" if AlefFina has mark's below
"uni066E0631" if AlefFina has mark's below

---

uniFD0E
uniFD2A
uni066E0631
uni066E0631.fina
uniFD0F
uniFD2B
uniFEAE
uni0631
uni0694.fina
uni0694
uni0693.fina
uni0693
uni0692.fina
uni0692
uniFB8D
uni0691
uniFEB0
uni0632
uni06EF.fina
uni06EF
uni0699.fina
uni0699
uniFB8B
uni0698
uni0697.fina
uni0697
uni0696.fina
uni0696
uni0695.fina
uniFC5C
uni0771.fina
uni0771
uni076C.fina
uni076C
uni076B.fina
uni076B
uni075B.fina
uni075B
+
"uni0627" and "uni0627.short" if AlefIso has mark's below

**Comment by graphicore** [comment]
Why would you kern these in the first place? I'm just using the kerning data as provided by you. "Ignore these" is hard, if possible (with a reasonable amount of work) at all after they have been kerned.

**Comment by graphicore** [comment]
Well, there is a "  ignore position <marked glyph sequence> (, <marked glyph sequence>)*;" keyword, so it is possible, however, I need to inject this into the kernFeatureGenerator at the right occasion. That kind of sucks, ufo-kerning is not made for this kind of thing :-(

**Comment by Tarobish** [comment]
Here is the Problem
please check the picture, "Adobe Arabic” compare to “Katibeh”
Normally “reh-Alef” it has to be kern like the one in the left side but when “Alef” has marks below it would be colliding
they solved this problem by moving marks below “Reh” when they are neighbor
“Alef” with the marks below has a different spacing when its alone

**Comment by graphicore** [comment]
pic is missing

**Comment by Tarobish** [comment]
Sorry, my bad i didn’t mention it is "dotlessbeh_High-ar”
when two or more characters from "dotlessbeh-ar.medi” family are neighbors the second one it must change to "dotlessbeh_High-ar”
this way we don’t have same tooth high just repeat after each other (its docent look good)
here is the sample of "Adobe Arabic" compare to “Jumhuria"

**Comment by graphicore** [comment]
Maybe you can't send the images as attachment of a mail reply.

**Comment by Tarobish** [comment]
![4d72eca4-cb42-11e5-93cd-57d6bf7092b9](https://cloud.githubusercontent.com/assets/8403973/12837056/96d94b64-cb73-11e5-8a28-6fc5da765e3b.png)
![4fc3eb3e-cb42-11e5-92ce-5d1bacf49859](https://cloud.githubusercontent.com/assets/8403973/12837059/996e86f0-cb73-11e5-86e0-9a404755d96e.png)

**Comment by Tarobish** [comment]
Maybe its better to do the same :)

**Comment by graphicore** [comment]
> Maybe its better to do the same :)

What do you mean? What is "the same"?

**Comment by Tarobish** [comment]
Like the Adobe Arabic, moving marks to the bottom 
Please compare the position of marks 
"Alef" with marks below, after "Reh" compare to the "Alef" which is alone 

![996e86f0-cb73-11e5-86e0-9a404755d96e](https://cloud.githubusercontent.com/assets/8403973/12900378/d80113e8-ce6a-11e5-8cef-d99a8485a36a.png)

**Comment by graphicore** [comment]
Yeah, I like that. I will try it. It's at this point probably better than ignoring the kerning, because I can apply it after the original kerning, so I don't have to mess around with your kerning data. Also, it may look better.

**Comment by Tarobish** [comment]
Awesome :)

**Comment by graphicore** [comment]
I made some testing tables to check what we are talking about:

http://tarobish.github.io/Katibeh/html/generated-pages.html#testsKern/Issue%20%2380.01%3A%20colliding%20bottom%20marks

http://tarobish.github.io/Katibeh/html/generated-pages.html#testsKern/Issue%20%2380.02%3A%20colliding%20bottom%20marks

http://tarobish.github.io/Katibeh/html/generated-pages.html#testsKern/Issue%20%2380.03%3A%20colliding%20bottom%20marks

The third one 80.03 is the worst, the others are not so bad actually.

**Comment by Tarobish** [comment]
it seems some ligatures and connection did not generated in the table. would please check them out
like uniFD0E, uniFD2A it you could that would be great . then ill let you know which characters are usable to fix them and get rid of the rest

**Comment by Tarobish** [comment]
Based on the generated test pages
we are fine from issues #80.01 and #80.02
lets fix #80.03 but please generate them all :) thanks

**Comment by graphicore** [comment]
>  seems some ligatures and connection did not generated in the table. would please check them out like uniFD0E, uniFD2A it you could that would be great . then ill let you know which characters are usable to fix them and get rid of the rest

The first two lines in 80.03 are FD0E the third and the fourth line are uniFD2A

![selection_070](https://cloud.githubusercontent.com/assets/393132/12987604/16d7fe94-d0fd-11e5-9a86-37f1c504a30a.png)

**Comment by Tarobish** [comment]
You are right but it dint general them all like شر or سر or شز or سژ
actually we don’t have these ligature with Persian and Arabic's form here!
and they are the most that we want

**Comment by graphicore** [comment]
I can add these for you and remove the others?

**Comment by Tarobish** [comment]
Please!
do you want me to write them all?

**Comment by graphicore** [comment]
how many are there?

**Comment by Tarobish** [comment]
in like 20 or 30

**Comment by graphicore** [comment]
actually I think only the variation in the second part matters. Plus if there are any marks below that can be added.

**Comment by Tarobish** [comment]
ok, please lets try these
i think we will be fine
را - زا - ژا
سرا - سزا - سژا - شرا - شزا - شژا
صرا - صزا - صژا - ضرا - ضزا - ضژا
برا - ترا - ثرا - پرا - یرا
بزا - تزا - ثزا - پزا - یزا
بژا - تژا - ثژا - پژا - یژا
also these character when the ligature or characters are in meddle form like
ببرا (last three characters) or بصرا (last three)
the rest doesn't matter

**Comment by graphicore** [comment]
I'll do

**Comment by Tarobish** [comment]
Great!

**Comment by graphicore** [comment]
It's all added at the top of the 80.03 table

**Comment by Tarobish** [comment]
Thanks

**Comment by Tarobish** [comment]
![screen shot 2016-02-11 at 12 46 54 pm](https://cloud.githubusercontent.com/assets/8403973/12990371/f93c76be-d0be-11e5-8090-69d29d5c60b6.png)
![screen shot 2016-02-11 at 12 46 41 pm](https://cloud.githubusercontent.com/assets/8403973/12990372/f94049c4-d0be-11e5-8e8f-8a3fd9d01f0f.png)
![screen shot 2016-02-11 at 12 46 13 pm](https://cloud.githubusercontent.com/assets/8403973/12990373/f94167be-d0be-11e5-9c08-be91bee4c40b.png)
![screen shot 2016-02-11 at 12 46 49 pm](https://cloud.githubusercontent.com/assets/8403973/12990374/f9431b7c-d0be-11e5-9164-9c0729f896ca.png)
![screen shot 2016-02-11 at 12 45 54 pm](https://cloud.githubusercontent.com/assets/8403973/12990380/f96bbc4e-d0be-11e5-8f1d-5eaadeceddea.png)
![screen shot 2016-02-11 at 12 46 07 pm](https://cloud.githubusercontent.com/assets/8403973/12990379/f96a67b8-d0be-11e5-8875-c6376cf0c84a.png)
![screen shot 2016-02-11 at 12 46 20 pm](https://cloud.githubusercontent.com/assets/8403973/12990375/f9550fb2-d0be-11e5-8ed9-c8130d2770de.png)
![screen shot 2016-02-11 at 12 46 00 pm](https://cloud.githubusercontent.com/assets/8403973/12990376/f959ea5a-d0be-11e5-8f5d-a43d692c46d9.png)
![screen shot 2016-02-11 at 12 46 27 pm](https://cloud.githubusercontent.com/assets/8403973/12990377/f95fe3d8-d0be-11e5-8b28-a6beb7a18f25.png)
![screen shot 2016-02-11 at 12 45 46 pm](https://cloud.githubusercontent.com/assets/8403973/12990378/f9623e8a-d0be-11e5-85cb-e28555ea5b63.png)

There you go :)

**Comment by graphicore** [comment]
The red dots are the cases that must work and the rest are "fantasy combinations" or at least very uncommon?

**Comment by Tarobish** [comment]
Yes, the res dots are the case the rest "fantasy combinations" and very uncommon in many cases  :)))

**Comment by Tarobish** [comment]
the point is vowels are really common in the Arabic, but in arabic language we just have these character
 ر - ز - س - ش - ص - ض
also sometimes in Persian which has them all plus ژ

**Comment by davelab6** [comment]
(No, github won't place images into issue comments that come in as mail
attachements)

**Comment by khaledhosny** [comment]
Off-topic, but that “serif” at end of ر is pretty weird, and not so good looking IMHO.

**Comment by graphicore** [comment]
@Tarobish Check it out. All your requested cases work now.
