### ISSUE TITLE
jeem-ar.medi 

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#82]
Dot's position its broken in "jeem-ar.medi" either in ligature or character positioning 
![screen shot 2016-02-03 at 7 04 50 pm](https://cloud.githubusercontent.com/assets/8403973/12804641/bf7b9f4c-caa9-11e5-8678-7280bc465ad6.png)

![screen shot 2016-02-03 at 7 05 48 pm](https://cloud.githubusercontent.com/assets/8403973/12804646/c497e1f2-caa9-11e5-99de-5cc2d880ed92.png)

**Comment by graphicore** [comment]
What should happen where? I think I've seen this fail somewhere in http://tarobish.github.io/Katibeh/html/generated-pages.html as well. May need some investigation.

**Comment by graphicore** [comment]
I think there is something wrong with the anchors. In the first image, if you don't like it like that it may be the anchor position. Or does it use the wrong anchor, then I have to decompose it differently.

In the second image it is similar: either the anchor is missing (you must solve that) or the decomposition uses a wrong mark for a non-existing anchor.

Can you please explain what you expect to see here and provide a live testing document.

**Comment by Tarobish** [comment]
It has to be something wrong with the decomposing. these two ligatures are using the same base and anchors, in the right one, dots position its wrong but the left one it works perfectly. same problem with the characters without ligatures. "jeem-ar.medi" its broken but "tcheh-ar.medi" its not and "jeem-ar.fina" it works but "tcheh-ar.fina" doesn't.

![screen shot 2016-02-08 at 9 53 06 am](https://cloud.githubusercontent.com/assets/8403973/12894235/721657d4-ce4a-11e5-95fd-9b51ca022de7.png)

![screen shot 2016-02-08 at 9 58 57 am](https://cloud.githubusercontent.com/assets/8403973/12894391/3ec6938e-ce4b-11e5-8e9c-597bd10ab312.png)

![screen shot 2016-02-08 at 9 52 46 am](https://cloud.githubusercontent.com/assets/8403973/12894404/575e8eba-ce4b-11e5-9683-8c408937c581.png)
![screen shot 2016-02-08 at 9 52 30 am](https://cloud.githubusercontent.com/assets/8403973/12894408/5bb2830e-ce4b-11e5-9635-bf53a6414bbc.png)
![screen shot 2016-02-08 at 10 02 27 am](https://cloud.githubusercontent.com/assets/8403973/12894410/5df9426a-ce4b-11e5-8692-700c860f32f4.png)
They have to be like these

![screen shot 2016-02-08 at 8 18 00 am](https://cloud.githubusercontent.com/assets/8403973/12894417/6e6b4102-ce4b-11e5-9433-cb56e6cd9505.png)

![screen shot 2016-02-08 at 8 17 48 am](https://cloud.githubusercontent.com/assets/8403973/12894420/72de3b36-ce4b-11e5-8af6-c7d61b32c98d.png)

**Comment by graphicore** [comment]
Ok, I think the solution here is pretty straight forward:

We need `xxx.center` marks for all marks that go to the center in the `fina` glyphs of the HAH-as-Base family of glyphs.

And for the init and medi versions of uni062D (one dot in the center) I made the wrong decomposition to `dotcenterar` where just the dot below should have been used.

I'll post a list of missing `xxx.center` in a few minutes.

**Comment by Tarobish** [comment]
Thanks :)

**Comment by graphicore** [comment]
[Ok, cool:](http://tarobish.github.io/Katibeh/html/live-testing.html#?eJxdkEEKwjAQRa9SIriykiZpGpOVqL2ArsRN0SiFWqUELIp3d2o7LczqvR/ebPJh10cdmGUvxTlbsODbsC0beGhCBdvf9+Xbw1TmGWBXRX2DVTTgZ7j0/+P5rOXaKBehUEbRqe5dYiQd5RRpjLSjnKIMo8xRjpHYDBEIJUZZavqoE8ox0rshAqGcohyj3FFiZNaijzqhhF+9FKH7b8ETHXMR89VBJFYam/JlKtWRfX85amh9)

![selection_060](https://cloud.githubusercontent.com/assets/393132/12931418/fdc9eab4-cf7d-11e5-9394-576e88150aba.png)

All needed marks were already in the font. But some ligatures are missing `center` anchors. You must do this:

[uni066E062D](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2312%3A%20ligature%2012%20%28uni066E062D%29)

[uniFC40](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2359%3A%20ligature%2059%20%28uniFC40%29)

A bit offtopic but for `uni0696.fina` some other ligatures also need a `center` anchor:

[uni066E0631](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%233%3A%20Ligature%2003%20%28uni066E0631%29)

[uni066E0631.fina](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%234%3A%20Ligature%2004%20%28uni066E0631.fina%29)

[uniFD0E](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2316%3A%20ligature%2016%20%28uniFD0E%29)

[uniFD2A](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2317%3A%20ligature%2017%20%28uniFD2A%29)

[uniFD0F](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2322%3A%20ligature%2022%20%28uniFD0F%29)

[uniFD2B](http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2323%3A%20ligature%2023%20%28uniFD2B%29)

**Comment by Tarobish** [comment]
Just perfect

**Comment by graphicore** [comment]
@Tarobish will you repair the ligatures?

**Comment by Tarobish** [comment]
Sure, what should i have to do?

**Comment by Tarobish** [comment]
I'm on it

**Comment by Tarobish** [comment]
For uni066E062D, the center anchor its right there but seems its not functioning as well as uniFC40, 
![screen shot 2016-02-09 at 3 58 02 pm](https://cloud.githubusercontent.com/assets/8403973/12934860/7ad87210-cf46-11e5-953b-7d520c9933f6.png)

![screen shot 2016-02-09 at 4 03 49 pm](https://cloud.githubusercontent.com/assets/8403973/12935020/9b2ad278-cf47-11e5-90c5-b7be9985d9cb.png)

uni066E0631, uni066E0631.fina, uniFD0E, uniFD0F and uniFD2B are looks good to me. didn't find anything, if we move ranchers a bit then it would be colliding in the small point sizes.

**Comment by graphicore** [comment]
> uni066E0631, uni066E0631.fina, uniFD0E, uniFD0F and uniFD2B are looks good to me. didn't find anything, if we move ranchers a bit then it would be colliding in the small point sizes.

In all tables it's just one column, where the second glyph is uni0696.fina:

![selection_064](https://cloud.githubusercontent.com/assets/393132/12935461/37a6b0ce-cf96-11e5-8f61-3895acf557f5.png)

See how the dot is at the top left? It's supposed to be more in the center, just as in `uni0696.fina` 
That kind of displacement happens when there is no anchor to attach to.

**Comment by graphicore** [comment]
Oh, and it needs a center anchor there.

**Comment by Tarobish** [comment]
Done :) both mirza and katibeh

**Comment by graphicore** [comment]
> For uni066E062D, the center anchor its right there but seems its not functioning as well as uniFC40, 

Ok, I have a theory, please read carefully and pay attention:

For ligatures, we do mark2ligature attachment. There the computer must decide to which anchor of the ligature a mark belongs. I don't know how glyphs decides this. However, in the ufo  I can see this:

![selection_065](https://cloud.githubusercontent.com/assets/393132/12935637/a2b3c8ec-cf97-11e5-990d-a1501d4f1a37.png)

Note that there are two anchors for top: `top_1` and `top_2`
and two for the bottom: `bottom_1` and `bottom_2`
Then there is just one `center` anchor.
Also there is `carret_1` which is the position where the cursor will be located within the ligature. 1 carret means the ligature is made of 2 parts, 2 carrets means the ligature is made out of 3 parts, and so on.

Within Glyphs, what are the names of the `top` and `bottom` anchors?
- Is it just `top` `top` `bottom` `bottom`?
- Is it `top_1` `top_2` `bottom_1` `bottom_2`? 

If it is like the first option, we need either two `center` anchors. _Maybe_ left and right of the carret.

If it is like the second option, what we need is `center_2` and _Maybe_ also `center_1`

I think the best implementation would be if just `center_2` is enough. So please rename these anchors to `center_2`

**Comment by Tarobish** [comment]
Also it been added to 
uniFD2A, uniFD0E, uniFD2B and uniFD0F

**Comment by graphicore** [comment]
probably, for all the ligatures where you just added it, we need to solve the anchor issue as well. Let's try to find the solution for uniFC40 first, so we can iterate faster.

**Comment by Tarobish** [comment]
its all top_1 top_2 bottom_1 bottom_2
and center_1
![screen shot 2016-02-09 at 5 00 27 pm](https://cloud.githubusercontent.com/assets/8403973/12935952/b18b03a6-cf4e-11e5-9f29-e4e91344ccd7.png)

**Comment by graphicore** [comment]
:+1:

So we want center_2

**Comment by Tarobish** [comment]
plz check it

**Comment by graphicore** [comment]
I filed a bug report in the Glyphs Forum https://forum.glyphsapp.com/t/problems-getting-custom-ligature-anchors-to-work/3846

**Comment by graphicore** [comment]
Ok, Looks allright now!

![selection_068](https://cloud.githubusercontent.com/assets/393132/12967419/a6a37d10-d066-11e5-9a0a-b291200adb53.png)
