### ISSUE TITLE
Error in extension part

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#83]
we don't need the extension, also i closed the colliding error in this case

![screen shot 2016-02-03 at 7 43 51 pm](https://cloud.githubusercontent.com/assets/8403973/12805327/4dd937f4-caaf-11e5-9411-e68a51839939.png)
![screen shot 2016-02-03 at 1 11 41 pm](https://cloud.githubusercontent.com/assets/8403973/12805329/506291a0-caaf-11e5-9706-bf6790d5e959.png)
![screen shot 2016-02-03 at 1 11 48 pm](https://cloud.githubusercontent.com/assets/8403973/12805331/5245c398-caaf-11e5-8b54-a1cf59ab4e95.png)

**Comment by graphicore** [comment]
Plesase check again. I removed collision-extension 03 and 04 from Katibeh.
