### ISSUE TITLE
"lam_alef-ar" and "lam_alef-ar.fina"

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#84]
in both case "lam_alef-ar" and "lam_alef-ar.fina" ligatures are broken

![screen shot 2016-02-03 at 7 53 02 pm](https://cloud.githubusercontent.com/assets/8403973/12805428/2cb7e2fe-cab0-11e5-85a9-dc11a3870be0.png)
![screen shot 2016-02-03 at 7 55 02 pm](https://cloud.githubusercontent.com/assets/8403973/12805430/2cdc3e42-cab0-11e5-8a12-ce84ce561ed8.png)

**Comment by graphicore** [comment]
Please add a live testing link plus screenshot.
Also post the link of the ligature testing page here: http://tarobish.github.io/Katibeh/html/generated-pages.html

**Comment by graphicore** [comment]
Ok, I see. This is because we never had an issue for these ligatures and the stuff we inherited from glyphs in insufficient.

Look at the fea excerpt below. These are the ligatures I never touched and where we have no issues/testing pages for.

I guess I should have a closer look at them?

Also, as in the ligature issues that we already have, I need your help to tell me in which languages and features (dlig/rlig) these ligatures should appear.

```
rlig featue:
    # TODO: the come from Glyphs and were not covered in the issues on Github
    sub uniFEDF uniFE8E by uniFEFB;
    sub uniFEE0 uniFE8E by uniFEFC;
    sub uniFEDF uniFE84 by uniFEF7;
    sub uniFEE0 uniFE84 by uniFEF8;
    sub uniFEDF uniFE88 by uniFEF9;
    sub uniFEE0 uniFE88 by uniFEFA;
    sub uniFEE0 uni0672.fina by uni06440672.fina;
    sub uniFEE0 uni0673.fina by uni06440673.fina;
    sub uniFEDF uniFE82 by uniFEF5;
    sub uniFEE0 uniFE82 by uniFEF6;
    sub uniFEDF uniFB51 by uni06440671;
    sub uniFEE0 uniFB51 by uni06440671.fina;

    sub uni06B5.medi uniFE8E by uni06B50627.fina;
    sub uni06B6.medi uniFE8E by uni06B60627.fina;
    sub uni06B7.medi uniFE8E by uni06B70627.fina;
    sub uni06B8.medi uniFE8E by uni06B80627.fina;
    sub uni076A.medi uniFE8E by uni076A0627.fina;

dlig feature:
    # TODO: the come from Glyphs and were not covered in the issues on Github
    sub uniFEE0 uni0672.fina by uni06440672.fina;
    sub uni0644 uni0672 by uni06440672.isol;
    sub uniFEE0 uni0673.fina by uni06440673.fina;
    sub uni0644 uni0673 by uni06440673.isol;

    sub uni06B5.medi uniFE8E by uni06B50627.fina;
    sub uni06B5 uni0627 by uni06B50627.isol;
    sub uni06B6.medi uniFE8E by uni06B60627.fina;
    sub uni06B6 uni0627 by uni06B60627.isol;
    sub uni06B7.medi uniFE8E by uni06B70627.fina;
    sub uni06B7 uni0627 by uni06B70627.isol;
    sub uni06B8.medi uniFE8E by uni06B80627.fina;
    sub uni06B8 uni0627 by uni06B80627.isol;

    sub uni076A.medi uniFE8E by uni076A0627.fina;
    sub uni076A uni0627 by uni076A0627.isol;
```

**Comment by graphicore** [comment]
[Here](http://tarobish.github.io/Mirza/html/live-testing.html#?eJytlt9OwjAUxl9lmYnRREjXdW2FK5DtBfTKeDN0mBkcBkZAjO9uy6Drn9MlZoSb9Zz9vu9rcxr2Ey5WVR2Owh1BKLwL62Jfz8q1KCzrtVgXn4/loRBLwr9qsV7m1btY5bL3KsjiCG+28+D6ap+ls2zcPPB0HMy/VVHVbrZVmaXZ9DYIXiqFpQjARNHGHkysdSOAG1EY87kRwK3FuM+NA25cYfc+Nw64tdgExBBl2MaamsQQJUSuhouyyn18DPCxwccA3+4WA7vFKnbi260T28Ao7DZNIsftWNPSRrCjgZ4cHbTdqNI47D6aQ5km1hDqHWMSZQVRzKxja9+nXiXqKNFOJeZVYo4S61TiXiXuKPEOJUYnHiXZMZVExVSSvwuNuGw4/LEI8+VmtbzkFdH9Y8Df5k3/y02dJiK7bZKGb2oG70vSd2o1ESsJdZLQziR9p14TsZIwJwnrTGLdmv9fG03FisJVFAOHk/S6decgZxEjyInXzuTMn5KIf/q3vJbfABhFdIDwACVPGI8IG0V8yGLyHP7+AW2qLqI=) is a rough test for the stuff shown above.
It indeed is exactly what you are complaining about!

This is Mirza, but we will have to solve this for both fonts anyways.

![screen shot 2016-02-05 at 23 49 21](https://cloud.githubusercontent.com/assets/393132/12861364/18b409e0-cc63-11e5-97ec-b56e116af372.png)

**Comment by Tarobish** [comment]
This ligatures it a default for all the Arabic script, when "lam-ar.init" and "lam-ar.medi" comes before "alef-ar.fina" it must change to the "lam_alef-ar" and "lam_alef-ar.fina"
as you see in the rough test, i didn't happen in many places

![screen shot 2016-02-05 at 5 36 54 pm](https://cloud.githubusercontent.com/assets/8403973/12863751/42bd9360-cc30-11e5-8524-b1be8a837191.png)

![screen shot 2016-02-05 at 5 37 00 pm](https://cloud.githubusercontent.com/assets/8403973/12863753/4d60be6e-cc30-11e5-9881-e6f5daf2ca66.png)

![screen shot 2016-02-05 at 5 37 07 pm](https://cloud.githubusercontent.com/assets/8403973/12863754/523fe324-cc30-11e5-9ff5-cfb15c458dc8.png)

**Comment by graphicore** [comment]
Sure I see, that's what I mean with what glyphs did for us is insufficient.

**Comment by Tarobish** [comment]
Unfortunately :( it makes extra works for you

**Comment by graphicore** [comment]
Sorry, this makes mo sense:

> , when "lam-ar.init" and "lam-ar.medi" comes before "alef-ar.fina" it must change to the "lam_alef-ar" and "lam_alef-ar.fina"

what you say is:

lam-ar.init + lam-ar.medi + alef-ar.fina = lam_alef-ar + lam_alef-ar.fina

But that means that we have one alef too much! (lam + alef + lam + alef)

**Comment by Tarobish** [comment]
Sorry :)
i mean lam-ar.init + alef-ar.fina
or
lam-ar.medi + alef-ar.fina

**Comment by graphicore** [comment]
Well, it looks like there is no version of this that stands in the middle of a word, it's always at the end of a word. Is it that what you meant?

**Comment by graphicore** [comment]
yeah, so either it is the `init + fina` combination or it is `medi + fina` but never `init + medi` or `medi + medi`

**Comment by Tarobish** [comment]
Yes it dose "uniFEFC" (lam_alef-ar.fina) it comes in the middle or at the end of the word
like:
ملاحظه
or
بلا

**Comment by Tarobish** [comment]
please take a look at
    sub uniFEDF uniFE8E by uniFEFB;
    sub uniFEE0 uniFE8E by uniFEFC;
for each combination it must be like these two :)

**Comment by graphicore** [comment]
Oh, and when it comes in the middle of the word it "breaks" he? I think the open type engine implements that for us, I don't think I have to do it.

**Comment by graphicore** [comment]
uniFEFB uniFEFC

right, I thought so. I think some of the existing ligature glyphs that we have here are never going to be used.

**Comment by Tarobish** [comment]
Yes, also in the table somewhere its broke in the isolate form like
uni06440673.isol

**Comment by graphicore** [comment]
yeah, that's why I called it a rough test. Some of these combinations are impossible.

**Comment by Tarobish** [comment]
in this case, we are fine then :) but we have uni06440673.isol as a "lam_alefWavyhamzabelow-ar.isol" so it has to function, right?

**Comment by Tarobish** [comment]
You are the boss :)

**Comment by graphicore** [comment]
> uni06440673.isol as a "lam_alefWavyhamzabelow-ar.fina" so it has to function, right?

That's uni06440673.isol:

![selection_047](https://cloud.githubusercontent.com/assets/393132/12864091/cd67fb08-cc81-11e5-89a1-b30a4b4083f8.png)

That would be `uniFEFB + Wavyhamzabelow-ar` in the end, right?

**Comment by Tarobish** [comment]
it could be anywhere, at the first, in the middle or at the end in arabic like
![screen shot 2016-02-05 at 6 38 00 pm](https://cloud.githubusercontent.com/assets/8403973/12864171/ce81a7e0-cc37-11e5-9638-f19cafe69336.png)

**Comment by graphicore** [comment]
Ok, got it. So this is the exception from the rule (of being a connected script), heh?

**Comment by Tarobish** [comment]
Yes :) if they are isol they could be anywhere and never get connected to the rest of the characters
in the isol form they are playing like a single isol character :)

**Comment by graphicore** [comment]
Ok, check this out:

http://tarobish.github.io/Katibeh/html/generated-pages.html#jomhuriaTests/collision-above-2

and make you own testing as in the initial description please.

Note that the "rough test" is not really useful, don't use it or copy and paste from it. It uses wrong input values.

**Comment by graphicore** [comment]
If your test doesn't yield in a pleasing result, please post a live testing page with your input here.
