### ISSUE TITLE
shaddaKasratan-ar

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#85]
"shaddaKasratan-ar" its broken

![screen shot 2016-02-03 at 8 06 53 pm](https://cloud.githubusercontent.com/assets/8403973/12805598/c8b317ea-cab1-11e5-8b4a-ad3f5322f0cd.png)

**Comment by graphicore** [comment]
Please use the "Live testing page" and post a link plus screenshot here. That way I don't have to guess how to enter the right characters. Thanks!

**Comment by Tarobish** [comment]
Sure :)

**Comment by Tarobish** [comment]
Just Shared from live testing page :)

**Comment by graphicore** [comment]
Where's the link?

**Comment by Tarobish** [comment]
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03Nt/YeLP35kSgYEpiCUixkYGhma6Bka6BSYiBiZWxsZWBmZ6ppUWUUi0AvFwiQQ== <http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03Nt/YeLP35kSgYEpiCUixkYGhma6Bka6BSYiBiZWxsZWBmZ6ppUWUUi0AvFwiQQ==>





http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK0KCjdbb7bf7lG4tfLGcoVb64HEjVVgNpAC8oCKUxJLQIYYGRia6RoY6RqYhBiYWBkbW5mY6BlbGkYp1QIAtSswUw== <http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK0KCjdbb7bf7lG4tfLGcoVb64HEjVVgNpAC8oCKUxJLQIYYGRia6RoY6RqYhBiYWBkbW5mY6BlbGkYp1QIAtSswUw==>

**Comment by Tarobish** [comment]
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03VtxYcatNAQJutt5qA8qmJJaAdBkZGJrpGhjpGpiEGJhZGRlYmRrqWViaRinVAgDwByRZ <http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03VtxYcatNAQJutt5qA8qmJJaAdBkZGJrpGhjpGpiEGJhZGRlYmRrqWViaRinVAgDwByRZ>

**Comment by graphicore** [comment]
Ok, so it's not easy for me to work that way.
1. Why post every link twice?
2. You post links without sufficient description. Please guide me.
3. Please add a screenshot _for every link_ that you post, that way I can control if I solved the issue.

**Comment by Tarobish** [comment]
![screen shot 2016-02-03 at 8 31 49 pm](https://cloud.githubusercontent.com/assets/8403973/12828441/b4a18452-cb39-11e5-8442-55f700575859.png)

http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03Nt/YeLP35kSgYEpiCUixkYGhma6Bka6BSYiBiZWxsZWBmZ6ppUWUUi0AvFwiQQ==

**Comment by Tarobish** [comment]
just fixed the photos problem :)

**Comment by graphicore** [comment]
Setting the language to "ar" or "fa" fixes it for me.

like here: http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kJRYB2clAnalgzTc239h4s/fmRKBgSmIJSLmRgaGZroGRroFJiJGBlbGRlbG5nqWFcZRSLQANCyMT

![selection_027](https://cloud.githubusercontent.com/assets/393132/12828808/0d358724-cb87-11e5-9f73-b4bd132e32c7.png)

**Comment by Tarobish** [comment]
Sorry i didn’t get it
i changed the setting to “fa” but its the same

http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kpSUC2clAnalgzTc239h4s/fmxBubQSRQKiWxBKTJyMDQTNfASNfAJMTI0MrQyMrASA9oT5RSLQBXRSdJ

**Comment by graphicore** [comment]
Probably the old font is still in your browser cache. When I reload by pressing `ctrl + shift + r` the cache refreshes.

![urlhosted - mozilla firefox_029](https://cloud.githubusercontent.com/assets/393132/12830051/976db140-cb8d-11e5-80e2-0fed9af7f05c.png)

**Comment by Tarobish** [comment]
ok, so ill close it :)
