### ISSUE TITLE
Dots Position 

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#88]
Center Dots position its broke in "tcheh-ar.fina" either on ligature or character position
![screen shot 2016-02-03 at 10 26 28 pm](https://cloud.githubusercontent.com/assets/8403973/12807617/3d84114c-cac5-11e5-870f-a4d651cf322b.png)

**Comment by graphicore** [comment]
Nice photo thanks, please add the link. I need that information. I can hardly reproduce your input by myself.
When the dot positioning is broken it is likely that it has to be fixed in Glyphs by you. With almost all mark positionings working in general, I'm pretty confident that I made the right thing, but the input is (what comes from Glyphs) is bad.

**Comment by Tarobish** [comment]
http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK03VtxYcatNAQJutt5qA8qmJJaAdBkZGJrpGhjpGpiEGJhZGRlYmRrqWViaRinVAgDwByRZ

**Comment by Tarobish** [comment]
Now it works perfect

**Comment by graphicore** [comment]
close?

**Comment by Tarobish** [comment]
Not yet

http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIKFJXkAPmpucGZValArrlRQQmQn5OYlw7kuSUWATnJQK2pYN03VtxqUwCCm61AGiiTklgC0mRkYGima2Cka2ARYmhhZWhgZWyiZ2RmGqVUCwC4eSOw

![screen shot 2016-02-08 at 10 11 01 am](https://cloud.githubusercontent.com/assets/8403973/12894567/5195a36e-ce4c-11e5-9e9d-1157065464dc.png)

**Comment by graphicore** [comment]
What do you expect?

**Comment by Tarobish** [comment]
three dots for "tcheh-ar.fina" it has to be align in the center like "jeem-ar.fina" or " tcheh-ar"

**Comment by graphicore** [comment]
Ah, understood. I'll have a look.

**Comment by graphicore** [comment]
Ok, I close this. The example now renders as like this:

![selection_061](https://cloud.githubusercontent.com/assets/393132/12931568/c980cfec-cf7e-11e5-873c-657a8d43749a.png)

In Arabic the ligature misses a `center` anchor, but that is covered in #82

![selection_062](https://cloud.githubusercontent.com/assets/393132/12931637/0cd30d0a-cf7f-11e5-81a5-75e660d20fb8.png)

**Comment by Tarobish** [comment]
Great :)
