### ISSUE TITLE
TahSmallTwoDotsabovear is not of type mark

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Katibeh#90]
It is apparently in Mirza already a mark.

**Comment by Tarobish** [comment]
Please let me know 
![screen shot 2016-02-05 at 10 26 35 am](https://cloud.githubusercontent.com/assets/8403973/12855239/2a97533a-cbf3-11e5-867c-ff7e12423323.png)

**Comment by graphicore** [comment]
TahSmallTwoDots**abovear** you show me _below_

**Comment by Tarobish** [comment]
Oh Sorry

![screen shot 2016-02-05 at 10 31 56 am](https://cloud.githubusercontent.com/assets/8403973/12855344/be442784-cbf3-11e5-8dd1-38b3f3e76437.png)

**Comment by graphicore** [comment]
You just changed that or is it like that all the time?

**Comment by Tarobish** [comment]
I didn't, it was like that

**Comment by graphicore** [comment]
Hmm, IC. Does it have the `_top` anchor?

**Comment by Tarobish** [comment]
It does

![screen shot 2016-02-05 at 10 37 37 am](https://cloud.githubusercontent.com/assets/8403973/12855483/8cb3b7d8-cbf4-11e5-87d3-b7bfa5bbd629.png)

**Comment by graphicore** [comment]
Shouldn't one of these anchors be displayed as a square?

**Comment by Tarobish** [comment]
They are all same

![screen shot 2016-02-05 at 10 40 41 am](https://cloud.githubusercontent.com/assets/8403973/12855552/00774900-cbf5-11e5-9eff-6c68cb0184df.png)

**Comment by graphicore** [comment]
Show me just the single dot mark. I rareley see this kind of v + dot. But the single dot is all over the place and working fine.

**Comment by Tarobish** [comment]
![screen shot 2016-02-05 at 10 49 52 am](https://cloud.githubusercontent.com/assets/8403973/12855795/4baf61e0-cbf6-11e5-989a-0f7a3089aca9.png)

**Comment by graphicore** [comment]
Ok, I don't know what is wrong here, but I can tell you that it is good in Mirza and bad in Katibeh.
In the images, compare the rightmost column.

Katibeh:

![selection_035](https://cloud.githubusercontent.com/assets/393132/12855903/5ecebcd4-cc42-11e5-8dfa-84de9de168ba.png)

http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2317%3A%20ligature%2017%20%28uniFD2A%29

Mirza:

![selection_036](https://cloud.githubusercontent.com/assets/393132/12855912/71fc5c1c-cc42-11e5-821c-cd91626b9f6f.png)

http://tarobish.github.io/Mirza/html/generated-pages.html#tests/Issue%20%2317%3A%20ligature%2017%20%28uniFD2A%29

**Comment by graphicore** [comment]
It must be something in Glyphs, because with Mirza we have prove that the mark-type is exported just fine with the glyph.

**Comment by Tarobish** [comment]
I'll compere it with mirza

KB STUDIO

**Comment by Tarobish** [comment]
Exactly!

KB STUDIO

**Comment by graphicore** [comment]
Ah, it's fixed now. Obviously you changed it in the meantime. Maybe when fixing #72

**Comment by Tarobish** [comment]
Great :)

KB STUDIO
