### ISSUE TITLE
Our  uni06AF uni06B0 etc. has no gafbar but Unicode says it has one (also Mirza has).

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Katibeh#92]
### This is Katibeh:

The gafbar comes in because we use the same features as in Mirza, which decomposes in the first row, but not in the second. The original characters are missing the gafbar completely. Thus, another error here is that the `_top` anchor of `gafbar-ar` is probably displaced or/and gafbar-ar is not a mark.

And the ring seems broken, too in the examle.

![selection_044](https://cloud.githubusercontent.com/assets/393132/12859844/19caea7e-cc59-11e5-868e-9c0d440ed89f.png)

http://tarobish.github.io/Katibeh/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIK5JQUAfmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK1qyhUGZo5u1ui0ApyhEJMHZjsZQAWBDHQaaGRKYgnIKiMDQzNdAyNdA9MQI0MrY2MrIyM9SyOTKKVaADrULJI=
### This is Mirza:

The second row is not being decomposed, hence in the Katibeh example these glyphs are composed differently (wrong?).

![selection_045](https://cloud.githubusercontent.com/assets/393132/12859854/2ba8ee30-cc59-11e5-9813-bc8736406d96.png)

http://tarobish.github.io/Mirza/html/live-testing.html#?eJyrVkrLzytRslIqNzEwUNJRKkmtKHHJLAIK5JQUAfmpucGZValArrlRQQmQn5OYlw7kAVnJQH2pYK1qyhUGZo5u1ui0ApyhEJMHZjsZQAWBDHQaaGRKYgnIKiMDQzNdAyNdA9MQI0MrY2MrIyM9SyOTKKVaADrULJI=

**Comment by Tarobish** [comment]
Please, check this out

**Comment by graphicore** [comment]
Good, now I get this with the link above:

![selection_048](https://cloud.githubusercontent.com/assets/393132/12864453/d773103e-cc8a-11e5-9bd9-0f80b5f11bef.png)
