### ISSUE TITLE
extension part

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#93]
It works perfect just I'm not sure it happens because of indesign or its error
the extension part has been applied when"Alef" docent have a marks below. it shouldn't be here :)
![screen shot 2016-02-06 at 10 20 24 am](https://cloud.githubusercontent.com/assets/8403973/12868445/cf5c1f18-ccbb-11e5-86d1-8758cc96a4d0.png)

**Comment by graphicore** [comment]
>  the extension part has been applied when"Alef" docent have a marks below. it shouldn't be here :)

But you asked me to do so.

see:

http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2360%3A%20Colliding%20glyph%20combinations%2001

made after you request in https://github.com/Tarobish/Katibeh/issues/68

**Comment by Tarobish** [comment]
Oh, no when it does (with mark below the baseline) 

KB STUDIO

**Comment by graphicore** [comment]
This should be better now, please check. If there are any marks below the base line that need to be added, please tell me.

Look also at these test pages ported from Jomhuria: 
http://tarobish.github.io/Katibeh/html/generated-pages.html#tests/Issue%20%2360%3A%20Colliding%20glyph%20combinations%2001
http://tarobish.github.io/Katibeh/html/generated-pages.html#jomhuriaTests/collision-below-1
