### ISSUE TITLE
Make a descriptive text for the font

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Katibeh#95]
For the same use cases as [this in Jomhuria](https://github.com/Tarobish/Jomhuria#jomhuria-font-project).

@Tarobish: I can help you to get it into shape, but you should deliver a starting point.

**Comment by Tarobish** [comment]
Katibeh, its a headline font based on Naskh and some qualities of the Thuluth script. with the help of Serif Katibeh represent an old script but by the help of new rules in font design it looks modern. something between tradition and modern fonts. in this font, ligatures, Arabic and Persian readers, see the character with are familiar with, to make them comfortable for reading text. unlike the other Arabic fonts, Katibeh has a Latin version which is design to have harmony for multilingual scripts.
