### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Katibeh#96]
- [x] @davelab6 to do a QA check
- [x] Put description in #95 in README.md 
- [x] README needs other info similar to https://github.com/Tarobish/Jomhuria/blob/gh-pages/README.md
- [x] set the gh-pages branch to default and remove the master branch
- [x] add description and URL to the top of the project page
- [x] regenerate ttfs without an intermediate OTF step to reduce filesize
- [x] perhaps remove some glyphs that are not used directly now, because of the decompositions

**Comment by graphicore** [comment]
The TTF is down from 335 kB to 188 kB

```
 Build/Katibeh-Regular.otf | Bin 165980 -> 164376 bytes
 Build/Katibeh-Regular.ttf | Bin 335616 -> 188356 bytes
```

**Comment by graphicore** [comment]
@Tarobish can you give me more rights for this and the Mirza repository? Then I can hopefully do most of the open tasks. 

![selection_080](https://cloud.githubusercontent.com/assets/393132/13338311/c7f00a04-dc20-11e5-9ce3-c87f21ffb693.png)

Then, if possible make me Admin, should look similar like here:

![selection_081](https://cloud.githubusercontent.com/assets/393132/13338444/bfaad544-dc21-11e5-87c6-5c19ad70e81c.png)

You can change my status back when this is done, but it's probably faster than via a video chat. 

Alternatively you can make this stuff yourself.

**Comment by Tarobish** [comment]
Why its a bit different?
![screen shot 2016-02-25 at 3 51 28 pm](https://cloud.githubusercontent.com/assets/8403973/13338683/e1b24a86-dbd7-11e5-8f35-757f8d895471.png)

**Comment by Tarobish** [comment]
![screen shot 2016-02-25 at 3 54 30 pm](https://cloud.githubusercontent.com/assets/8403973/13338720/1e4d8762-dbd8-11e5-9fb7-1c584b5abe99.png)

**Comment by graphicore** [comment]
Hmm, maybe you can't do this in the repository. It's different because I used another type of repository for the screenshot. I had no better example at hand :-/

**Comment by graphicore** [comment]
Yeah, so apparently I used a repository of an organisation, because it had more than one user ... but this is a user repository and there it doesn't work the same way :-(

**Comment by Tarobish** [comment]
:( so what is the solution?

**Comment by graphicore** [comment]
Here are two things for you to do:

>  set the gh-pages branch to default and remove the master branch

![selection_082](https://cloud.githubusercontent.com/assets/393132/13339456/fcbce75e-dc28-11e5-9bae-67ab4fd21376.png)

>  add description and URL to the top of the project page

![selection_083](https://cloud.githubusercontent.com/assets/393132/13339457/04773d32-dc29-11e5-8de0-c5e3681d721d.png)

![selection_084](https://cloud.githubusercontent.com/assets/393132/13339466/2710b8d2-dc29-11e5-8a36-7db0b988f32d.png)
1. For Katibeh insert at description: "Katibeh Arabic Font Project" (just the same as the headline in README.md)
2. For Katibeh Insert at Website: "http://tarobish.github.io/Katibeh/"
3. save.

Mirza:
1. For Mirza insert at description: "Mirza Arabic Font Project" (just the same as the headline in README.md)
2. For Mirza Insert at Website: "http://tarobish.github.io/Mirza/"
3. save.

**Comment by Tarobish** [comment]
Please check it out

**Comment by graphicore** [comment]
perfect, thanks!

**Comment by Tarobish** [comment]
Sure :)

**Comment by davelab6** [comment]
OK I have confirmation that instead of a copyright notice like https://github.com/Tarobish/Katibeh/blob/gh-pages/OFL.txt#L1

you can do something like https://github.com/NDISCOVER/Arima-Font  and metapolator, where there are 3 files
- https://github.com/NDISCOVER/Arima-Font/blob/master/AUTHORS.txt#L8-L9
- https://github.com/NDISCOVER/Arima-Font/blob/master/CONTRIBUTORS.txt#L12-L13
- https://github.com/NDISCOVER/Arima-Font/blob/master/OFL.txt#L1

This is cleaner.

**Comment by davelab6** [comment]
FullName expected Katibeh, got Katibeh-Regular
fsType expected: 0 got fsType: 8

**Comment by graphicore** [comment]
```
<namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">Katibeh</namerecord>
```

and

```
<fsType value="00000000 00000000"/>
```

**Comment by graphicore** [comment]
I also updated the Copyright infos in Katibeh, Mirza and Jomhuria to the above mentioned style.

**Comment by davelab6** [comment]
Great!
